# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to identify your site in the RSS feed
# And to set the generated HTML <title> on the main pages.
title: Luke Gude's Blog
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog of Luke Gude, where I write about technology, programming, and other interests.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lukegude.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lukegude
github_username:  lukegude

# Build settings
markdown: kramdown

# Permalink structure
permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-postcss

# Jekyll PostCSS configuration
postcss:
  config: postcss.config.js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - README.md
  - .gitignore